### ISSUE TITLE
bug-紧急！-账本中查看发票图片

### ISSUE THREAD

**Issue by yyhews** [jefferscn/xiexin#2]
通过账本界面，查看发票详情，点击图片预览，直接跳出空屏，且无法回退操作，需要重启APP才可以

![image](https://user-images.githubusercontent.com/73337415/97145468-387fb880-17a1-11eb-8ac1-22128f2a6096.png)
![image](https://user-images.githubusercontent.com/73337415/97145515-49302e80-17a1-11eb-91cd-69ad1627ddc0.png)

**Comment by jefferscn** [comment]
IOS 1.0.6
Android 1.0.9
中修正
